# Generated by Django 3.0.6 on 2020-12-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
