# Generated by Django 3.0.6 on 2020-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0011_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.FloatField(null=True),
        ),
    ]
